const workoutStorageKey = "workout-life-exercises-v2";
const dailyStorageKey = "workout-life-daily-v2";
const startDate = "2026-09-01";
const firebaseConfig = { apiKey: "AIzaSyCfvqQWLB8NJqmaH0k2G0wPcbJJjz2Vu4A", authDomain: "kaimemo-58bad.firebaseapp.com", projectId: "kaimemo-58bad", storageBucket: "kaimemo-58bad.firebasestorage.app", messagingSenderId: "308069117698", appId: "1:308069117698:web:c61a57853abb7e8ffb1c1b" };
const goals = [[9,65.7],[10,65.3],[11,64.9],[12,64.5],[1,64.2],[2,63.9],[3,63.5],[4,63.2],[5,62.9],[6,62.5],[7,62.3],[8,61.9]];
const habits = [["noJuice","ジュースなし"],["noSnacks","お菓子なし"],["lowCarb","炭水化物少な目"],["lowFruit","果物少な目"],["moreVeg","野菜多め"],["moreWater","水をたくさん"],["oneMeal","1日1食"]];
const groups = {
  "運動":["筋トレ","傾斜ウォーキング","週末テニス"]
};
const $ = (s) => document.querySelector(s);
const fmt = new Intl.DateTimeFormat("ja-JP",{year:"numeric",month:"long",day:"numeric",weekday:"short"});
const shortFmt = new Intl.DateTimeFormat("ja-JP",{month:"short",day:"numeric",weekday:"short"});
let docRef=null, firestoreReady=false, editingId=null, activeFilter="all", selected=new Set();
let workouts=loadWorkouts(), daily=loadDaily();
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function normalizeEquipmentName(value){return String(value)==="傾斜ウォーキング（Mリーグ）"?"傾斜ウォーキング":String(value);}
function normalizeItems(w){if(Array.isArray(w.items))return w.items.filter(i=>i?.equipment).map(i=>({area:i.area||"その他",equipment:normalizeEquipmentName(i.equipment)}));const e=w.equipment||w.exercise;return e?[{area:w.area||"その他",equipment:normalizeEquipmentName(e)}]:[];}
function normalizeWorkouts(v){return (Array.isArray(v)?v:[]).map(w=>({...w,id:w.id==null?crypto.randomUUID():String(w.id),items:normalizeItems(w),note:w.note||"",createdAt:w.createdAt||`${w.date}T00:00:00.000Z`})).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt));}
function loadWorkouts(){try{return normalizeWorkouts(JSON.parse(localStorage.getItem(workoutStorageKey)||"[]")).filter(w=>w.date>=startDate);}catch{return [];}}
function loadDaily(){try{const v=JSON.parse(localStorage.getItem(dailyStorageKey)||"{}");return v&&typeof v==="object"&&!Array.isArray(v)?v:{};}catch{return {};}}
function saveWorkouts(){localStorage.setItem(workoutStorageKey,JSON.stringify(workouts));if(firestoreReady&&docRef)docRef.set({lifeWorkouts:workouts},{merge:true}).catch(e=>console.error("運動履歴の保存に失敗しました。",e));saved();}
function saveDaily(){localStorage.setItem(dailyStorageKey,JSON.stringify(daily));if(firestoreReady&&docRef)docRef.set({lifeDailyRecords:daily},{merge:true}).catch(e=>console.error("食事・体重の保存に失敗しました。",e));saved();}
function saved(){const s=$("#saveStatus");s.textContent="共有保存しました ✓";clearTimeout(saved.t);saved.t=setTimeout(()=>s.textContent="食事・体重・運動は端末間で同期されます",1800);}
function record(){return daily[$("#dailyDate").value]||{mealNote:"",habits:{},weight:null};}
function updateRecord(patch){const date=$("#dailyDate").value;daily[date]={...record(),...patch,updatedAt:new Date().toISOString()};saveDaily();dashboard();renderMealHistory();}
function renderHabits(){$("#habitChecks").innerHTML=habits.map(([k,l])=>`<label class="habit-check"><input type="checkbox" value="${k}"><span>${l}</span></label>`).join("");}
function loadDate(){const r=record(),date=new Date(`${$("#dailyDate").value}T00:00:00`);$("#mealDateLabel").textContent=`${fmt.format(date)}の食事`;$("#mealNote").value=r.mealNote||"";$("#weightInput").value=r.weight||"";document.querySelectorAll("#habitChecks input").forEach(i=>i.checked=Boolean(r.habits?.[i.value]));$("#mealForm button[type=submit]").textContent=(r.mealNote||Object.keys(r.habits||{}).length)?"食事の変更を保存":"この日の食事を保存";if(!editingId)resetWorkout();dashboard();}
function goal(){const m=new Date(`${$("#dailyDate").value}T00:00:00`).getMonth()+1;return goals.find(g=>g[0]===m)||goals[0];}
function latestWeight(){return Object.entries(daily).filter(([,r])=>Number(r.weight)).sort(([a],[b])=>b.localeCompare(a))[0]||null;}
function offsetDate(date,days){const d=new Date(`${date}T00:00:00`);d.setDate(d.getDate()+days);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function weightOn(date){const w=Number(daily[date]?.weight);return w?`${w.toFixed(1)}kg`:"--";}
function dashboard(){renderWeightTrend();const [m,g]=goal(),latest=latestWeight(),w=latest?Number(latest[1].weight):null,selectedDate=$("#dailyDate").value,achieved=Boolean(w&&w<=g);$("#monthlyGoalLabel").textContent=`${m}月末の目標`;$("#monthlyGoalValue").textContent=`${g.toFixed(1)} kg`;$("#previousWeight").textContent=weightOn(offsetDate(selectedDate,-1));$("#twoDaysAgoWeight").textContent=weightOn(offsetDate(selectedDate,-2));$("#weightRemaining").textContent=w?(achieved?"達成！":`${(w-g).toFixed(1)}kg`):"--";$("#weightDays").textContent=`${Object.values(daily).filter(r=>Number(r.weight)).length}日`;$("#goalMessage").textContent=w?(achieved?"今月の目標達成。ご褒美発動！":`あと ${(w-g).toFixed(1)}kg で今月の目標`):"体重を記録すると進捗が表示されます";$("#goalProgress").style.width=w?`${Math.max(4,Math.min(100,((66-w)/4.1)*100))}%`:"0%";$("#rewardCard").classList.toggle("achieved",achieved);}
function renderWeightTrend(){
  let panel=document.querySelector('#weightTrend');
  if(!panel){panel=document.createElement('section');panel.id='weightTrend';panel.className='panel weight-trend';panel.innerHTML='<h3>日ごとの体重推移</h3><div class="weight-chart"></div><details><summary>日付別の体重を見る</summary><div class="weight-table"></div></details>';document.querySelector('.weight-zone').append(panel);}
  const entries=Object.entries(daily).filter(([date,r])=>/^\d{4}-\d{2}-\d{2}$/.test(date)&&Number.isFinite(Number(r?.weight))&&Number(r?.weight)>0).sort(([a],[b])=>a.localeCompare(b));
  const chart=panel.querySelector('.weight-chart'),table=panel.querySelector('.weight-table');chart.replaceChildren();table.replaceChildren();
  if(!entries.length){chart.textContent='体重を記録すると推移が表示されます。';return;}
  const weights=entries.map(([,r])=>Number(r.weight)),low=Math.min(...weights)-.3,high=Math.max(...weights)+.3;
  const time=date=>Date.parse(date+'T00:00:00Z'),first=time(entries[0][0]),span=time(entries[entries.length-1][0])-first;
  const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 700 240');svg.setAttribute('role','img');svg.setAttribute('aria-label','日ごとの体重推移。正確な値は日付別の体重一覧で確認できます。');
  const add=(tag,attrs,text)=>{const node=document.createElementNS(svg.namespaceURI,tag);Object.entries(attrs).forEach(([k,v])=>node.setAttribute(k,v));if(text!==undefined)node.textContent=text;svg.append(node);return node;};
  for(let i=0;i<4;i++){const value=low+(high-low)*i/3,y=195-i*55;add('line',{x1:60,x2:675,y1:y,y2:y,stroke:'#d9e2dc'});add('text',{x:53,y:y+4,'text-anchor':'end','font-size':13,fill:'#667b75'},value.toFixed(1));}
  const points=entries.map(([date,r])=>({date,w:Number(r.weight),x:span?60+(time(date)-first)/span*615:367.5,y:195-(Number(r.weight)-low)/(high-low)*165}));
  add('polyline',{points:points.map(p=>`${p.x},${p.y}`).join(' '),fill:'none',stroke:'#237a58','stroke-width':3});
  points.forEach(p=>{const circle=add('circle',{cx:p.x,cy:p.y,r:4,fill:'#237a58'}),title=document.createElementNS(svg.namespaceURI,'title');title.textContent=`${p.date}: ${p.w.toFixed(1)}kg`;circle.append(title);});
  add('text',{x:60,y:225,'font-size':13,fill:'#667b75'},entries[0][0]);if(entries.length>1)add('text',{x:675,y:225,'text-anchor':'end','font-size':13,fill:'#667b75'},entries[entries.length-1][0]);chart.append(svg);
  const caption=document.createElement('p');caption.textContent=`最新 ${weights[weights.length-1].toFixed(1)}kg ／ ${entries.length}日分（未記録日は点を表示しません）`;chart.append(caption);
  const t=document.createElement('table');t.innerHTML='<thead><tr><th>日付</th><th>体重</th></tr></thead>';const body=document.createElement('tbody');[...entries].reverse().forEach(([date,r])=>{const row=document.createElement('tr');[date,`${Number(r.weight).toFixed(1)}kg`].forEach(text=>{const cell=document.createElement('td');cell.textContent=text;row.append(cell);});body.append(row);});t.append(body);table.append(t);
}
function renderMealHistory(){const list=$("#mealHistoryList"),entries=Object.entries(daily).filter(([,r])=>Boolean(r.mealNote?.trim())||Object.values(r.habits||{}).some(Boolean)).sort(([a],[b])=>b.localeCompare(a));list.innerHTML="";if(!entries.length){list.innerHTML='<div class="empty-state">食事記録はまだありません。</div>';return;}entries.forEach(([date,r])=>{const item=document.createElement("article"),head=document.createElement("button"),note=document.createElement("p"),habitList=document.createElement("div"),done=habits.filter(([key])=>r.habits?.[key]).map(([,label])=>label);item.className="meal-history-item";head.type="button";head.dataset.date=date;head.textContent=`${fmt.format(new Date(`${date}T00:00:00`))}　編集`;head.setAttribute("aria-label",`${date}の食事を編集`);note.className="meal-history-note";note.textContent=r.mealNote?.trim()||"食事内容の記録なし";habitList.className="meal-history-habits";done.forEach(label=>{const tag=document.createElement("span");tag.textContent=label;habitList.append(tag);});item.append(head,note,habitList);list.append(item);});}
function equipment(){const map=new Map();Object.entries(groups).forEach(([a,names])=>names.forEach(e=>map.set(`${a}::${e}`,{area:a,equipment:e})));workouts.flatMap(w=>w.items).forEach(i=>map.set(`${i.area}::${i.equipment}`,i));return map;}
function renderPicker(){const by=new Map();equipment().forEach((v,k)=>{if(!by.has(v.area))by.set(v.area,[]);by.get(v.area).push([k,v]);});$("#equipmentPicker").innerHTML="";by.forEach((items,a)=>{const section=document.createElement("section");section.className="equipment-group";section.innerHTML=`<h4>${a}</h4><div class="equipment-choices"></div>`;items.forEach(([k,v])=>{const b=document.createElement("button");b.type="button";b.dataset.key=k;b.className="equipment-choice";b.textContent=v.equipment;b.setAttribute("aria-pressed",String(selected.has(k)));section.querySelector("div").append(b);});$("#equipmentPicker").append(section);});$("#selectionStatus").textContent=`${selected.size}種類を選択中`;}
function startWeek(){const d=new Date(),diff=d.getDay()===0?-6:1-d.getDay();d.setDate(d.getDate()+diff);d.setHours(0,0,0,0);return d;}
function renderHistory(){const start=startWeek(),list=activeFilter==="week"?workouts.filter(w=>new Date(`${w.date}T00:00:00`)>=start):workouts;$("#historyList").innerHTML="";if(!list.length){$("#historyList").innerHTML='<div class="empty-state">運動記録はまだありません。</div>';return;}list.forEach(w=>{const n=$("#workoutItemTemplate").content.firstElementChild.cloneNode(true);n.dataset.id=w.id;n.querySelector("time").textContent=shortFmt.format(new Date(`${w.date}T00:00:00`));n.querySelector("h3").textContent=`${w.items.length}種類`;w.items.forEach(i=>{const c=document.createElement("span");c.textContent=i.equipment;n.querySelector(".workout-stats").append(c);});if(w.note)n.querySelector(".workout-note").textContent=w.note;else n.querySelector(".workout-note").remove();$("#historyList").append(n);});}
function resetWorkout(){editingId=null;selected=new Set();$("#noteInput").value="";$("#formTitle").textContent="今日やった運動";$("#submitButton").textContent="運動を保存";renderPicker();}
function editWorkout(w){editingId=w.id;$("#dailyDate").value=w.date;loadDate();editingId=w.id;selected=new Set(w.items.map(i=>`${i.area}::${i.equipment}`));$("#noteInput").value=w.note;$("#formTitle").textContent=`${shortFmt.format(new Date(`${w.date}T00:00:00`))}の運動を編集`;$("#submitButton").textContent="変更を保存";renderPicker();$("#workoutForm").scrollIntoView({behavior:"smooth"});$("#noteInput").focus({preventScroll:true});}
$("#mealForm").addEventListener("submit",e=>{e.preventDefault();const h={};document.querySelectorAll("#habitChecks input").forEach(i=>h[i.value]=i.checked);updateRecord({mealNote:$("#mealNote").value.trim(),habits:h});});
$("#weightForm").addEventListener("submit",e=>{e.preventDefault();updateRecord({weight:Number($("#weightInput").value)});});
$("#dailyDate").addEventListener("change",loadDate);
$("#mealHistoryList").addEventListener("click",e=>{const button=e.target.closest("button[data-date]");if(!button)return;resetWorkout();$("#dailyDate").value=button.dataset.date;loadDate();$("#mealForm").scrollIntoView({behavior:"smooth"});$("#mealNote").focus({preventScroll:true});});
$("#equipmentPicker").addEventListener("click",e=>{const b=e.target.closest("button[data-key]");if(!b)return;selected.has(b.dataset.key)?selected.delete(b.dataset.key):selected.add(b.dataset.key);renderPicker();});
$("#workoutForm").addEventListener("submit",e=>{e.preventDefault();if(!selected.size){$("#selectionStatus").textContent="1つ以上選んでください";return;}const map=equipment(),old=workouts.find(w=>w.id===editingId),w={id:editingId||crypto.randomUUID(),date:$("#dailyDate").value,items:[...selected].map(k=>map.get(k)).filter(Boolean),note:$("#noteInput").value.trim(),createdAt:old?.createdAt||new Date().toISOString()};workouts=normalizeWorkouts(editingId?workouts.map(x=>x.id===editingId?w:x):[w,...workouts]);saveWorkouts();renderHistory();resetWorkout();});
$("#clearForm").addEventListener("click",resetWorkout);
$("#historyList").addEventListener("click",e=>{const item=e.target.closest(".workout-item");if(!item)return;const w=workouts.find(x=>x.id===item.dataset.id);if(e.target.closest(".edit-button")&&w)editWorkout(w);if(e.target.closest(".delete-button")){workouts=workouts.filter(x=>x.id!==item.dataset.id);saveWorkouts();renderHistory();renderPicker();}});
document.querySelectorAll(".filter-button").forEach(b=>b.addEventListener("click",()=>{activeFilter=b.dataset.filter;document.querySelectorAll(".filter-button").forEach(x=>x.classList.toggle("active",x===b));renderHistory();}));
function startSync(){if(typeof firebase==="undefined")return;if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);docRef=firebase.firestore().collection("data").doc("workout-log");docRef.onSnapshot(s=>{if(!s.exists){firestoreReady=true;docRef.set({lifeWorkouts:workouts,lifeDailyRecords:daily},{merge:true});return;}const data=s.data(),needsInitialLifeData=!Object.hasOwn(data,"lifeWorkouts")||!Object.hasOwn(data,"lifeDailyRecords");workouts=normalizeWorkouts(data.lifeWorkouts||[]).filter(w=>w.date>=startDate);daily=data.lifeDailyRecords&&typeof data.lifeDailyRecords==="object"?data.lifeDailyRecords:daily;localStorage.setItem(workoutStorageKey,JSON.stringify(workouts));localStorage.setItem(dailyStorageKey,JSON.stringify(daily));firestoreReady=true;if(needsInitialLifeData)docRef.set({lifeWorkouts:workouts,lifeDailyRecords:daily},{merge:true});loadDate();renderHistory();renderPicker();renderMealHistory();},e=>console.error("共有データの同期に失敗しました。",e));}
$("#dailyDate").value=today()<startDate?startDate:today();$("#dailyDate").min=startDate;$("#todayLabel").textContent="2026年9月1日スタート";renderHabits();$("#goalTimeline").innerHTML=goals.map(([m,g])=>`<div><span>${m}月末</span><strong>${g.toFixed(1)}kg</strong></div>`).join("");loadDate();renderHistory();renderMealHistory();startSync();
